// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"altastore-api/application/use_case/authentication/login"
	"altastore-api/application/use_case/product/create_product"
	"altastore-api/infrastructure/persistence/repository/db"
	"altastore-api/infrastructure/transport/http"
	"github.com/jinzhu/gorm"
)

// Injectors from container.go:

func LoginHandler(db2 *gorm.DB) login.LoginHandler {
	loginRepository := db.NewLoginRepository(db2)
	accountRepository := db.NewAccountRepository(db2)
	customerRepository := db.NewCustomerRepository(db2)
	loginHandler := login.NewLoginHandler(loginRepository, accountRepository, customerRepository)
	return loginHandler
}

func CreateProductHandler(db2 *gorm.DB) create_product.CreateProductHandler {
	infrastructureRequest := request.NewRequest()
	productRepository := db.NewProductRepository(db2)
	createProductHandler := create_product.NewCreateProductHandler(infrastructureRequest, productRepository)
	return createProductHandler
}
